### ISSUE TITLE
Error when instrumenting H2 database jar

### ISSUE THREAD

**Issue by alvaroc1** [kamon-io/kamon-jdbc#24]
Kamon 2.0. Not sure what the error means:
```
[play-dev-mode-akka.actor.default-dispatcher-6] ERROR 2019-08-06 13:03:51  Logger : Error => org.h2.Driver with message Cannot resolve type description for kamon.instrumentation.jdbc.DriverConnectAdvice. Class loader: Common ClassLoader: file:/Users/alvarocarrasco/.ivy2/cache/com.h2database/h2/jars/h2-1.4.196.jar: java.lang.IllegalStateException: Cannot resolve type description for kamon.instrumentation.jdbc.DriverConnectAdvice
        at kanela.agent.libs.net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:159)
        at kanela.agent.libs.net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1407)
        at kanela.agent.libs.net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getDeclaredMethods(TypeDescription.java:8045)
        at kanela.agent.libs.net.bytebuddy.asm.Advice.to(Advice.java:334)
        at kanela.agent.libs.net.bytebuddy.asm.Advice$WithCustomMapping.to(Advice.java:10946)
        at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Transformer$ForAdvice$Entry$ForUnifiedAdvice.resolve(AgentBuilder.java:2528)
        at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Transformer$ForAdvice.transform(AgentBuilder.java:2314)
        at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Transformer$Compound.transform(AgentBuilder.java:2614)
        at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:10126)
        at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10551)
        at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10514)
        at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10280)
        at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10890)
        at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10837)
        at java.security.AccessController.doPrivileged(Native Method)
        at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10437)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
        at play.runsupport.classloader.DelegatingClassLoader.loadClass(DelegatingClassLoader.java:34)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
        at kamon.instrumentation.sbt.KanelaOnSystemClassLoader.loadClass(KanelaOnSystemClassLoader.java:39)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
        at kamon.instrumentation.sbt.KanelaOnSystemClassLoader.loadClass(KanelaOnSystemClassLoader.java:39)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
        at java.util.ServiceLoader$LazyIterator.access$700(ServiceLoader.java:323)
```

This is on a play 2.7 application with this on the application.conf file:
```
...
kanela.modules.jdbc.within += "^org.h2.Driver"
kanela.modules.jdbc.within += "^org.h2.jdbc..*"
```

**Comment by ivantopo** [comment]
Hey @alvaroc1, this is not an issue on this module but rather related to how SBT loads the H2 classes when running in development mode. This issue has been just fixed by a [new release of the SBT Kanela Runner](https://github.com/kamon-io/sbt-kanela-runner/releases/tag/v2.0.2) plugin. Upgrade and the error should be gone!
