### ISSUE TITLE
NullPointerException for mysql db

### ISSUE THREAD

**Issue by yarosman** [kamon-io/kamon-jdbc#26]
Database can't be initialized because of java.lang.NullPointerException
[Project for reproducing](https://github.com/yarosman/kamon-play-anorm)
It works with h2 database but fails with mysql 5.7

```scala
Caused by: java.lang.NullPointerException: null
	at kamon.instrumentation.jdbc.HikariPoolCreatePoolEntryMethodAdvice$.exit(HikariInstrumentation.scala:117)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:482)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:534)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at play.api.db.HikariCPConnectionPool.$anonfun$create$1(HikariCPModule.scala:56)
	at scala.util.Try$.apply(Try.scala:213)
	at play.api.db.HikariCPConnectionPool.create(HikariCPModule.scala:52)
	at play.api.db.PooledDatabase.createDataSource(Databases.scala:230)
	at play.api.db.DefaultDatabase.dataSource$lzycompute(Databases.scala:141)
```

**Comment by yarosman** [comment]
It was fixed in 2.0.1 release
